-- BMS IMS — Supabase cloud database
-- Run this entire script once in Supabase Dashboard > SQL Editor.
-- Uses the publishable browser key + Row Level Security.

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  item_code text not null unique,
  item_name text not null,
  description text default '',
  category text not null,
  subcategory text default '',
  brand text default '',
  model text default '',
  part_number text default '',
  unit text not null default 'PCS',
  location text default 'BMS Store',
  minimum_stock integer not null default 0 check (minimum_stock >= 0),
  maximum_stock integer not null default 0 check (maximum_stock >= 0),
  opening_stock integer not null default 0 check (opening_stock >= 0),
  supplier text default '',
  remarks text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  transaction_id text not null unique,
  item_id bigint not null references public.items(id) on delete restrict,
  transaction_type text not null check (transaction_type in ('STOCK_IN','STOCK_OUT','ADJUSTMENT')),
  quantity integer not null check (quantity <> 0),
  reference text default '',
  supplier text default '',
  issued_to text default '',
  work_order text default '',
  area text default '',
  reason text default '',
  received_by text default '',
  issued_by text default '',
  user_name text default '',
  remarks text default '',
  transaction_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists idx_transactions_item_id on public.transactions(item_id);
create index if not exists idx_transactions_date on public.transactions(transaction_date desc);

alter table public.items enable row level security;
alter table public.transactions enable row level security;

-- v1 is a trusted internal tool. These policies allow the app's publishable-key
-- browser client to read/write. Add Supabase Auth later for per-user security.
drop policy if exists "BMS IMS items access" on public.items;
create policy "BMS IMS items access"
on public.items for all
to anon, authenticated
using (true)
with check (true);

drop policy if exists "BMS IMS transactions access" on public.transactions;
create policy "BMS IMS transactions access"
on public.transactions for all
to anon, authenticated
using (true)
with check (true);

grant select, insert, update, delete on public.items to anon, authenticated;
grant select, insert, update, delete on public.transactions to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Seed the 49 real BMS inventory master items. Opening stock = 0.
insert into public.items
(item_code,item_name,description,category,unit,location,minimum_stock,maximum_stock,opening_stock)
values
('PVC-001','PVC CONDUIT 20MM','PVC CONDUIT 20MM','Electrical','PCS','BMS Store',0,0,0),
('PVC-002','PVC SADDLE CUP 20MM','PVC SADDLE CUP 20MM','Electrical','PCS','BMS Store',0,0,0),
('ELEC-CAB-001','RED - PVC CABLE 2.5 MM (MEGA)','RED - PVC CABLE 2.5 MM (MEGA)','Electrical','MTR','BMS Store',0,0,0),
('ELEC-CAB-002','BLACK - PVC CABLE 2.5 MM (MEGA)','BLACK - PVC CABLE 2.5 MM (MEGA)','Electrical','MTR','BMS Store',0,0,0),
('ELEC-CAB-003','GREEN - PVC CABLE 2.5 MM (MEGA)','GREEN - PVC CABLE 2.5 MM (MEGA)','Electrical','MTR','BMS Store',0,0,0),
('ELEC-CAB-004','BLACK - PVC CABLE 1.5 MM (MEGA)','BLACK - PVC CABLE 1.5 MM (MEGA)','Electrical','MTR','BMS Store',0,0,0),
('ELEC-CAB-005','RED - PVC CABLE 1.5 MM (MEGA)','RED - PVC CABLE 1.5 MM (MEGA)','Electrical','MTR','BMS Store',0,0,0),
('BMS-CAB-001','18 AWG CABLE (ALANTEK)','18 AWG CABLE (ALANTEK)','BMS','MTR','BMS Store',0,0,0),
('ELV-CAB-001','CAT6 CABLE (ALANTEK)','CAT6 CABLE (ALANTEK)','ELV','MTR','BMS Store',0,0,0),
('CON-001','MASKING TAPE','MASKING TAPE','Consumables','ROLL','BMS Store',0,0,0),
('ELEC-003','GI ELBOW 20MM','GI ELBOW 20MM','Electrical','PCS','BMS Store',0,0,0),
('BMS-REL-001','RELAY 24VAC','RELAY 24VAC','BMS','PCS','BMS Store',0,0,0),
('BMS-REL-002','TERMINAL BASE RELAY','TERMINAL BASE RELAY','BMS','PCS','BMS Store',0,0,0),
('CON-002','INSULATION TAPE','INSULATION TAPE','Consumables','ROLL','BMS Store',0,0,0),
('ELEC-004','PVC ELBOW 20MM','PVC ELBOW 20MM','Electrical','PCS','BMS Store',0,0,0),
('TOOL-004','BLOWER BORCH','BLOWER BORCH','Tools','PCS','BMS Store',0,0,0),
('TOOL-005','VACUUM','VACUUM','Tools','PCS','BMS Store',0,0,0),
('TOOL-006','UPS PROLINK','UPS PROLINK','Tools','PCS','BMS Store',0,0,0),
('TOOL-007','4 STEP LADDER','4 STEP LADDER','Tools','PCS','BMS Store',0,0,0),
('TOOL-008','8 STEP LADDER','8 STEP LADDER','Tools','PCS','BMS Store',0,0,0),
('ELEC-005','13A 3-PIN PLUG','13A 3-PIN PLUG','Electrical','PCS','BMS Store',0,0,0),
('ELEC-006','FLEXIBLE METAL CONDUIT','FLEXIBLE METAL CONDUIT','Electrical','MTR','BMS Store',0,0,0),
('ELEC-007','FLEXIBLE NON-METALLIC CONDUIT','FLEXIBLE NON-METALLIC CONDUIT','Electrical','MTR','BMS Store',0,0,0),
('TOOL-009','STANLEY TOOL SET','STANLEY TOOL SET','Tools','SET','BMS Store',0,0,0),
('ELV-002','RJ45 CONNECTOR','RJ45 CONNECTOR','ELV','PCS','BMS Store',0,0,0),
('CON-003','SOLDER WIRE','SOLDER WIRE','Consumables','ROLL','BMS Store',0,0,0),
('CON-004','STAILESS STEEL CLEANER','STAILESS STEEL CLEANER','Consumables','PCS','BMS Store',0,0,0),
('CON-005','PULLER ROPE','PULLER ROPE','Consumables','MTR','BMS Store',0,0,0),
('ELEC-008','T5 LED TUBE','T5 LED TUBE','Electrical','PCS','BMS Store',0,0,0),
('BMS-SEN-001','TEMPERATURE SENSOR','TEMPERATURE SENSOR','BMS','PCS','BMS Store',0,0,0),
('BMS-SEN-002','DPT FLL TUBE STAIRCASE SENSOR','DPT FLL TUBE STAIRCASE SENSOR','BMS','PCS','BMS Store',0,0,0),
('TOOL-010','SOLDER PROSKIT','SOLDER PROSKIT','Tools','SET','BMS Store',0,0,0),
('BMS-SEN-003','DUCT TEMPRATURE SENSOR','DUCT TEMPRATURE SENSOR','BMS','PCS','BMS Store',0,0,0),
('ELEC-009','GI BAR SADDLE 20MM','GI BAR SADDLE 20MM','Electrical','PCS','BMS Store',0,0,0),
('PVC-003','PVC SADDLE 20MM','PVC SADDLE 20MM','Electrical','PCS','BMS Store',0,0,0),
('PVC-004','PVC SOCKET 20MM','PVC SOCKET 20MM','Electrical','PCS','BMS Store',0,0,0),
('ELEC-010','GI SOCKET 20MM','GI SOCKET 20MM','Electrical','PCS','BMS Store',0,0,0),
('ELEC-MCB-001','MCB 20A','MCB 20A','Electrical','PCS','BMS Store',0,0,0),
('ELEC-MCB-002','MCB 32A','MCB 32A','Electrical','PCS','BMS Store',0,0,0),
('CON-006','SILICON SEALANT','SILICON SEALANT','Consumables','PCS','BMS Store',0,0,0),
('CON-007','WD40 SPRAY','WD40 SPRAY','Consumables','PCS','BMS Store',0,0,0),
('CON-008','PVC WALLPLUG','PVC WALLPLUG','Consumables','BOX','BMS Store',0,0,0),
('CON-009','METAL WALLPLUG','METAL WALLPLUG','Consumables','BOX','BMS Store',0,0,0),
('ELEC-011','GI CIRCULAR BOX 2 WAY 20MM','GI CIRCULAR BOX 2 WAY 20MM','Electrical','PCS','BMS Store',0,0,0),
('ELEC-012','GI CIRCULAR BOX 2 WAY 25MM','GI CIRCULAR BOX 2 WAY 25MM','Electrical','PCS','BMS Store',0,0,0),
('PVC-005','PVC CIRCULAR BOX 2 WAY 20MM','PVC CIRCULAR BOX 2 WAY 20MM','Electrical','PCS','BMS Store',0,0,0),
('ELEC-013','GI T-BOX 25MM','GI T-BOX 25MM','Electrical','PCS','BMS Store',0,0,0),
('ELEC-014','GI T-BOX 20MM','GI T-BOX 20MM','Electrical','PCS','BMS Store',0,0,0),
('PVC-006','PVC T-BOX 20MM','PVC T-BOX 20MM','Electrical','PCS','BMS Store',0,0,0)
on conflict (item_code) do nothing;
