'use strict';

/**
 * Builds the GitHub Pages static demo.
 *
 *   npm run build:pages
 *
 * The Pages build is 100% static (no server, no external requests):
 *
 *   docs/                     complete standalone static site
 *     index.html              shell that loads js/local-backend.js
 *     css/, js/app.js, js/charts.js   shared frontend, copied from public/
 *     js/local-backend.js     browser implementation of the REST API
 *                             (demo dataset inlined at build time)
 *     .nojekyll               disables Jekyll processing on GitHub Pages
 *
 *   index.html (repo root)  GitHub Pages entry point — Pages serves the repo
 *                           root, so this shell loads the app from docs/.
 *                           (GitHub Pages is configured with source = main @ /)
 */

const fs = require('node:fs');
const path = require('node:path');
const { CATEGORIES, ITEMS, TXNS } = require('../seed');

const ROOT = path.join(__dirname, '..');
const DOCS = path.join(ROOT, 'docs');

function copy(src, dest) {
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.copyFileSync(src, dest);
}

/* 1. clean output */
fs.rmSync(DOCS, { recursive: true, force: true });
fs.mkdirSync(DOCS, { recursive: true });

/* 2. shared frontend assets (identical UI to the Node version) */
copy(path.join(ROOT, 'public/css/style.css'), path.join(DOCS, 'css/style.css'));
copy(path.join(ROOT, 'public/js/app.js'), path.join(DOCS, 'js/app.js'));
copy(path.join(ROOT, 'public/js/charts.js'), path.join(DOCS, 'js/charts.js'));
copy(path.join(ROOT, 'public/js/transaction-enhancements.js'), path.join(DOCS, 'js/transaction-enhancements.js'));

/* 3. demo dataset, generated from seed.js so it never drifts */
const now = new Date().toISOString();
const categories = CATEGORIES.map(([name, description], i) => ({ id: i + 1, name, description, created_at: now }));
const items = ITEMS.map((r, i) => ({
  id: i + 1,
  item_code: r[0],
  item_name: r[1],
  description: r[2],
  category: r[3],
  subcategory: r[4],
  brand: r[5],
  model: r[6],
  part_number: r[7],
  unit: r[8],
  location: r[9],
  minimum_stock: r[10],
  maximum_stock: r[11],
  opening_stock: r[12],
  supplier: r[13],
  remarks: r[14],
  created_at: now,
  updated_at: now,
}));
const idByCode = new Map(items.map((it) => [it.item_code, it.id]));
const transactions = TXNS.map(([code, type, qty, date, extra], i) => ({
  id: i + 1,
  transaction_id: `TXN-2026-${String(i + 1).padStart(6, '0')}`,
  item_id: idByCode.get(code),
  transaction_type: type,
  quantity: qty,
  reference: extra.reference || '',
  supplier: extra.supplier || '',
  issued_to: extra.issued_to || '',
  work_order: extra.work_order || '',
  area: extra.area || '',
  reason: extra.reason || '',
  user: extra.user || '',
  remarks: extra.remarks || '',
  transaction_date: date,
  created_at: now,
}));
const seed = { categories, items, transactions };

/* 4. local backend with the demo dataset inlined (works from any base path) */
let backend = fs.readFileSync(path.join(ROOT, 'pages-src/js/local-backend.js'), 'utf8');
const PLACEHOLDER = '/*__BMS_IMS_SEED__*/ null';
if (!backend.includes(PLACEHOLDER)) {
  throw new Error('Seed placeholder missing in pages-src/js/local-backend.js');
}
backend = backend.replace(PLACEHOLDER, JSON.stringify(seed));
fs.mkdirSync(path.join(DOCS, 'js'), { recursive: true });
fs.writeFileSync(path.join(DOCS, 'js/local-backend.js'), backend);

/* 5. standalone docs/ shell */
copy(path.join(ROOT, 'pages-src/index.html'), path.join(DOCS, 'index.html'));

/* 6. nojekyll */
fs.writeFileSync(path.join(DOCS, '.nojekyll'), '');

/* 7. repo-root index.html — GitHub Pages entry point (loads the app from docs/) */
let rootShell = fs.readFileSync(path.join(ROOT, 'pages-src/index.html'), 'utf8');
rootShell = rootShell
  .replace(/href="css\//g, 'href="docs/css/')
  .replace(/src="js\//g, 'src="docs/js/');
rootShell = `<!-- Generated by scripts/build-pages.js — do not edit by hand.
     GitHub Pages entry point: Pages serves this repository's root, so this
     shell loads the static BMS IMS app (which lives in docs/) at the site URL. -->
${rootShell}`;
fs.writeFileSync(path.join(ROOT, 'index.html'), rootShell);

console.log(
  `[build-pages] built — docs/ static site + root index.html ` +
    `(${categories.length} categories, ${items.length} items, ${transactions.length} transactions inlined)`
);
